AllCops:
  TargetRubyVersion: '3.1.2'
  DisplayCopNames: true
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - bin/*
    - config/**/*
    - config/application.rb
    - db/**/*

Style/Documentation:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Layout:
  Metrics/LineLength:
    Max: 120

Metrics/ParameterLists:
  Max: 10

Metrics/ClassLength:
  Max: 250

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Max: 50

Metrics/MethodLength:
  Max: 50
  Exclude:
    - lib/tasks/*.rake

Metrics/CyclomaticComplexity:
  Enabled: false